name: Continous Intergration and Deployment

on:
  push:
    branches: master

jobs:
  docker-image:
    runs-on: ubuntu-latest
    steps:
      - name: Check out Code
        uses: actions/checkout@v2

      - name: Setup .Net 5
        uses: actions/Setup-dotnet@v2
        with:
          dotnet-version: '5.0.x'

      - name: Pull SQL Server
        run: | 
          docker run -d -e "ACCEPT_EULA=Y" -e "SA_PASSWORD=@dmin123" -e "MSSQL_PID=Express" -p 1433:1433 -d mcr.microsoft.com/mssql/server:2019-latest 

      - name: Wait for 5 seconds 😴
        uses: jakejarvis/wait-action@master
        with:
          time: '5s'

      - name: Restore dependencies 
        run: dotnet restore

      - name: Build app
        run: dotnet build -c Release --no-restore

      - name: Run automated tests
        env:
          ConnectionStrings__DefaultConnection: Server=localhost;Database=IntergradeDbTest;User=sa;Password=@dmin123
        run: dotnet test -c Release --no-build



